### PR TITLE
Integration updates

### PR DESCRIPTION
**Pull request by hallas**
Hi @sperand-io 

It was a pleasure to meet in the Hangout.

Here's my initial changes and some questions that I have. There'll probably be more to follow up but this is the starting point. As I mentioned on the call, we have a client waiting for this and this integration is to facilitate his use case, however we have many more clients for whom this will of benefit.

We're looking to upgrade the Mojn integration into a high quality integration and your help is much appreciated in that regard, I'm a quick learner so your time won't be wasted.

Commit message:

Starting to bring the integration back up to date.
- Added region and sync options.
- Added custom script in addition to the main script.
- Added identify and sync pixels as tags.
- Will now load both main (old) and custom tags upon initialisation.
- Uses the `.load` api to load pixels now, for example in the identify
  implementation.
- Implemented the page call to sync on every new page.

Questions: 
- (lib/index.js#38) In the tests, it appears that the custom script (nested load after the main script) is loaded more times than the main script, so there is some kind of failing mechanic to not re-create tags that already have been loaded that is failing?
- (lib/index.js#99) I'm not sure if this was intended but in every page load when I tested a new anonymous id was created, but isn't analytics.js supposed to group them together somehow if it knows a person is the same (for example based on session cookies?)
- (test/index.test.js#99,104,115) I'm missing some kind of mechanic to verify that the implementations were actually called correctly? I've seen in other integrations the use of `analytics.called` but I'm not sure how it works.

That's the questions for this round. Your help is much appreciated.

### CODE REVIEW

**Comment by hallas** [comment]
I'll take care of the circleci errors.

**Comment by f2prateek** [comment]
Try to send each of those changes in their own PR (or at least commits) next time so that it's easier to review.

**Comment by f2prateek** [comment]
We'll also need a description of the new options so we can show them in our UI.

**Comment by hallas** [comment]
@f2prateek 

I'll send new changes individually. I'd like some help with the questions in order to move on.

The options are described as follows:
- region: This is the region to which the api calls are directed. Generally we ask clients to select region based on geographical proximity but in some cases also for legal purposes, for example if you only want your data stored somewhere under EU law or US laws. The options are 'eu' or 'na' where 'eu' should be default.
- sync: this is a boolean that determines if the segment anonymous/known IDs should be synced to Mojn for data matching purposes.

**Comment by hallas** [comment]
@f2prateek @sperand-io 

Hi guys. Sorry to be asking so soon.

Can you give us an idea of a time of when we'll be able to move this further along?

Thanks so much.

**Comment by f2prateek** [comment]
Sorry haven't had time to take a deeper look, but tests are still broken which is the main reason why I haven't merged this yet.

**Comment by hallas** [comment]
@f2prateek 

No worries. I wanted to get answers on my questions before adding more changes. Then I'll take a look at the CircleCI errors.

At this point in time I don't want this merged before I've had a chance to address the issues raised in the questions.

Hope this makes sense. Sorry for the inconvenience mate. :smile:

**Comment by sperand-io** [comment]
@hallas I'm so sorry for the delay here — I thought I responded last week, guess it never went through. 

> (lib/index.js#38) In the tests, it appears that the custom script (nested load after the main script) is loaded more times than the main script, so there is some kind of failing mechanic to not re-create tags that already have been loaded that is failing?

Hmm, no, there's no mechanism to noop on an existing tag, but given the logic you've written we shouldn't be seeing it loaded multiple times — the callback to `.load` should only be triggered once. https://github.com/segmentio/analytics.js-integration/blob/master/lib/protos.js#L253-L296

Maybe we can hop on another quick screenshare and step through the tests to get a handle on why that might be happening...

> (lib/index.js#99) I'm not sure if this was intended but in every page load when I tested a new anonymous id was created, but isn't analytics.js supposed to group them together somehow if it knows a person is the same (for example based on session cookies?)

The anonymousId uses cookies/localstorage as its storage mechanisms and persists across visits/sessions unless it's deliberately [reset](https://segment.com/docs/libraries/analytics.js/#reset-logout) as it is in the tests here: https://github.com/mojn/analytics.js-integration-mojn/blob/master/test/index.test.js#L25

> (test/index.test.js#99,104,115) I'm missing some kind of mechanic to verify that the implementations were actually called correctly? I've seen in other integrations the use of analytics.called but I'm not sure how it works.

Ah, yea the mechanism for checking that the tag loader works correctly is slightly different from the usual suspects of stubbing and spying on the 3rd party lib's methods. Lucking the tester has a `.loaded` method which employed like so: https://github.com/segment-integrations/analytics.js-integration-twitter-ads/blob/master/test/index.test.js#L88

Let me know if that helps!

**Comment by hallas** [comment]
@sperand-io 

Hi, okay this all makes sense to me. I'll push an update tomorrow and I'll ping you again if I have more questions.

**Comment by hallas** [comment]
@sperand-io do you have a reverse `loaded` to see that something specifically was not loaded?

**Comment by hallas** [comment]
@sperand-io Only one question left. What's the reverse of "loaded"? -- notLoaded or something to that effect

**Comment by hallas** [comment]
@f2prateek @sperand-io ready for a review

**Comment by hallas** [comment]
Also, our client says he is now feeding email addresses using the query string into Segment, any idea how I would access those in the Integration?

**Comment by hallas** [comment]
@f2prateek @sperand-io 

Ping :-)

**Pull request merged**
